using System;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Utility;

namespace Content.Client._Floof.Vore;

[GenerateTypedNameReferences]
public sealed partial class VoreMenu : DefaultWindow
{
    public EntityUid Owner { get; private set; }

    public VoreMenu()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += _ => Close();
    }

    public void SetEntity(EntityUid owner)
    {
        Owner = owner;
    }
}
