using System;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.GameObjects;
using Content.Shared._Floof.Vore;
namespace Content.Client._Floof.Vore;

[GenerateTypedNameReferences]
public sealed partial class VoreMenu : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public VoreMenu()
    {
        IoCManager.InjectDependencies(this); 
        RobustXamlLoader.Load(this);
        Load();
        CloseButton.OnPressed += _ => Close();
        AllowPred.OnToggled += args => Save();
        AllowPrey.OnToggled += args => Save();
        /* TODO work in progress
        Digest.OnToggled += args => Save();
        AllowSound.OnToggled += args => Save();
        ValueA.ValueChanged += args => Save();
        ValueB.ValueChanged += args => Save();
        ValueC.ValueChanged += args => Save();
        DigestSpeed.ValueChanged += args => Save();
        */
    }

    private void Save()
    {
        _cfg.SetCVar(VoreCVars.VoreAllowPred, AllowPred.Pressed);
        _cfg.SetCVar(VoreCVars.VoreAllowPrey, AllowPrey.Pressed);
        /* TODO work in progress
        _cfg.SetCVar(VoreCVars.VoreDigest, Digest.Pressed);
        _cfg.SetCVar(VoreCVars.VoreAllowSound, AllowSound.Pressed);

        _cfg.SetCVar(VoreCVars.VoreR, (int)ValueA.Value);
        _cfg.SetCVar(VoreCVars.VoreG, (int)ValueB.Value);
        _cfg.SetCVar(VoreCVars.VoreB, (int)ValueC.Value);

        _cfg.SetCVar(VoreCVars.VoreDigestSpeed, (int)DigestSpeed.Value);
        _cfg.SaveToFile();
        */
        SendSettings();
    }

    private void Load()
    {
        AllowPred.Pressed = _cfg.GetCVar(VoreCVars.VoreAllowPred);
        AllowPrey.Pressed = _cfg.GetCVar(VoreCVars.VoreAllowPrey);
        /* TODO work in progress
        Digest.Pressed = _cfg.GetCVar(VoreCVars.VoreDigest);
        AllowSound.Pressed = _cfg.GetCVar(VoreCVars.VoreAllowSound);

        ValueA.Value = _cfg.GetCVar(VoreCVars.VoreR);
        ValueB.Value = _cfg.GetCVar(VoreCVars.VoreG);
        ValueC.Value = _cfg.GetCVar(VoreCVars.VoreB);
        DigestSpeed.Value = _cfg.GetCVar(VoreCVars.VoreDigestSpeed);
        */
        //TODO REMOVE AFTER FIX OF CVARS NOT LOADING PROPERLY
        SendSettings();
    }

    private void SendSettings()
    {
        var ev = new VoreSettingsEvent
        {
            AllowPred = _cfg.GetCVar(VoreCVars.VoreAllowPred),
            AllowPrey = _cfg.GetCVar(VoreCVars.VoreAllowPrey)
        };

        _entityManager.EntityNetManager.SendSystemNetworkMessage(ev);
    }
}